server:
  port: 8080
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
spring:
  jpa:
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/daopuerp?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhanglingzhe0820
  aop:
    auto: true
    proxy-target-class: false